
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: es_demo
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  port: 3306

# test:
#   <<: *default
#   database:

# production:
#   <<: *default
#   database: 
